version: '3'
services:
  api:
    build: .
    networks:
      - my-network

  MongoDB:
    image: mongo:latest
    volumes:
      - ./MongoDB/data:/data/db
    networks:
      - my-network

  lighttpd:
    image: bullseyegolf-lighttpd:latest
    volumes:
      - ./nginx/certs:/certs
    networks:
      - my-network
    ports:
      - 443:443

networks:
  my-network:
