version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
  proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/certs:/etc/ssl/private
