version: '3'
services:
  api:
    build: .
    networks:
      - my-network

  MongoDB:
    image: mongo:latest
    volumes:
      - ./MongoDB/data:/data/db
    networks:
      - my-network

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/certs:/etc/ssl/private
    networks:
      - my-network
    ports:
      - 80:80 # Might not be neccecary
      - 443:443

networks:
  my-network:
